"""
=============================================================================
netcdf_io.py  —  Shared CF-1.10 + ACDD-1.3 writer helpers for the project
=============================================================================

Single source of truth for writing NetCDF outputs in this project
(Scotese paleo-DEMs, Zhou geochem correction, Young 2022 dyntopo
composition test, etc.).

Every NetCDF written via these helpers carries:

  GLOBAL attributes (CF-1.10 + ACDD-1.3 minimum set):
    Conventions          "CF-1.10, ACDD-1.3"
    title                short human-readable description
    summary              ~2-sentence description of what's in the file
    comment              free-form provenance (which script generated it,
                         from what inputs, what conventions, sign convention,
                         etc.) — the verbose explanation
    institution          "EarthByte Group, University of Sydney"
    source               specific software/script + version + commit
    references           upstream literature citations
    history              ISO-8601 timestamp + tool + command (CF convention:
                         each new processing step appends to this string)
    creator_name/_email  ACDD
    date_created         ISO-8601

  COORDINATE-VARIABLE attributes (CF — essential for GMT/QGIS recognition):
    lat:  units="degrees_north", standard_name="latitude",   axis="Y", long_name
    lon:  units="degrees_east",  standard_name="longitude",  axis="X", long_name

  DATA-VARIABLE attributes (per-variable):
    units                e.g. "m", "mm yr-1", "Gt C yr-1"
    long_name            human-readable description
    standard_name        CF standard name if applicable
    _FillValue           explicit for float types (default NaN)

Two entry points:

  open_cf_dataset(path, ...)        — context manager. Use like:
      with open_cf_dataset(out_fp, title=..., summary=..., comment=...) as ds:
          ds.create_lat_lon(lat_arr, lon_arr)
          ds.create_data_var("M_corrected", arr, units="m", long_name="...")

  write_cf_grid(path, fields, ...)  — one-shot convenience. Writes a single
      2D grid (lat × lon) with multiple data variables.

The helper also produces sensible defaults (zlib compression, deflate=4 +
shuffle, lossy bitgroom for floats via least_significant_digit=3 by default)
so files come out compact without needing per-call tuning.

USAGE
    from netcdf_io import write_cf_grid

    write_cf_grid(
        out_path=Path("data/corrected_Scotese/50Ma_corrected_SW.nc"),
        lat=lat, lon=lon,
        fields={
            "M_corrected": (M_final, {"units": "m",
                                       "long_name": "Geochem-corrected paleo-elevation",
                                       "standard_name": "surface_altitude"}),
            "M_orig":      (M, {"units": "m", "long_name": "Original Scotese & Wright 2018 paleo-elevation"}),
            "delta":       (M_final - M, {"units": "m", "long_name": "Correction applied"}),
        },
        title="Geochem-assimilated Scotese & Wright paleo-DEM, 50 Ma",
        summary="Zhou et al. 2024 correction applied to Scotese & Wright 2018 PaleoDEMs.",
        comment="Generated by assimilate_scotese.py from CSV crustal-thickness "
                "geochemistry samples reconstructed via Scotese-Wright 2023 plate model.",
        source="assimilate_scotese.py v1.0 (Paleotopo_data_assimilation, git <hash>)",
        references="Scotese & Wright 2018; Zhou et al. 2024 ESS; Scotese & Wright 2023",
        target_age_ma=50,
    )

This module is intentionally dependency-free beyond netCDF4 + numpy.
=============================================================================
"""
from __future__ import annotations
import os
import subprocess
import sys
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
from netCDF4 import Dataset


__all__ = [
    "DEFAULT_INSTITUTION",
    "CF_CONVENTIONS",
    "write_cf_grid",
    "open_cf_dataset",
    "amend_existing_cf_headers",
    "git_describe",
]


# ---------------------------------------------------------------------------
# Project-wide defaults
# ---------------------------------------------------------------------------

DEFAULT_INSTITUTION = "EarthByte Group, University of Sydney"
CF_CONVENTIONS = "CF-1.10, ACDD-1.3"
DEFAULT_CREATOR_NAME = "Dietmar Müller (and EarthByte group)"
DEFAULT_CREATOR_EMAIL = "dietmar.muller@sydney.edu.au"

# Compression / quantisation defaults
DEFAULT_COMPLEVEL = 4         # zlib deflate level (4 = sweet spot)
DEFAULT_SHUFFLE = True        # HDF5 shuffle filter (improves deflate for fp)
DEFAULT_LSD = 3               # least_significant_digit bitgroom (≈5e-4 rel.err)
DEFAULT_CHUNK_2D = (256, 512) # good chunk size for 1–4° global grids

# CF lat/lon attribute templates
_LAT_ATTRS = dict(units="degrees_north", standard_name="latitude",
                  long_name="Latitude", axis="Y")
_LON_ATTRS = dict(units="degrees_east",  standard_name="longitude",
                  long_name="Longitude", axis="X")


# ---------------------------------------------------------------------------
# Provenance helpers
# ---------------------------------------------------------------------------

def git_describe(repo_root: Path | None = None) -> str:
    """Return `git describe --always --dirty` for the repo containing
    `repo_root` (or the cwd if None). Returns 'unknown' on any failure."""
    try:
        cwd = Path(repo_root) if repo_root is not None else Path.cwd()
        out = subprocess.run(
            ["git", "-C", str(cwd), "describe", "--always", "--dirty=-dirty",
             "--abbrev=10"],
            capture_output=True, text=True, timeout=5,
        )
        if out.returncode == 0:
            return out.stdout.strip()
    except Exception:  # noqa: BLE001
        pass
    return "unknown"


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _history_line(tool: str, source: str | None) -> str:
    cmd = " ".join(sys.argv) if sys.argv else "(interactive)"
    src = f" [{source}]" if source else ""
    return f"{_now_iso()} {tool}{src}: {cmd}"


# ---------------------------------------------------------------------------
# One-shot writer (most callers want this)
# ---------------------------------------------------------------------------

def write_cf_grid(
    out_path: Path,
    lat: np.ndarray,
    lon: np.ndarray,
    fields: dict[str, tuple[np.ndarray, dict]],
    *,
    title: str,
    summary: str,
    comment: str,
    source: str,
    references: str = "",
    target_age_ma: int | float | None = None,
    institution: str = DEFAULT_INSTITUTION,
    creator_name: str = DEFAULT_CREATOR_NAME,
    creator_email: str = DEFAULT_CREATOR_EMAIL,
    extra_globals: dict | None = None,
    complevel: int = DEFAULT_COMPLEVEL,
    shuffle: bool = DEFAULT_SHUFFLE,
    lsd: int | None = DEFAULT_LSD,
    chunks_2d: tuple[int, int] = DEFAULT_CHUNK_2D,
    overwrite: bool = True,
) -> Path:
    """Write a single 2D-grid NetCDF (lat × lon × n_fields) with full CF
    headers. Returns the output path on success.

    fields : dict mapping variable name → (data_array, attrs_dict). Required
             per-var attrs: 'units', 'long_name'. Optional: 'standard_name',
             'flag_values', 'flag_meanings', etc.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if overwrite and out_path.exists():
        out_path.unlink()

    # Atomic write via .tmp + rename
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    if tmp.exists():
        tmp.unlink()
    with Dataset(tmp, "w", format="NETCDF4") as ds:
        _set_global_attrs(
            ds, title=title, summary=summary, comment=comment,
            source=source, references=references,
            institution=institution, creator_name=creator_name,
            creator_email=creator_email, target_age_ma=target_age_ma,
            extra_globals=extra_globals,
        )
        H, W = len(lat), len(lon)
        registration = "gridline" if (H % 2 == 1 and W % 2 == 1) else "pixel"
        ds.grid_registration = registration
        ds.node_offset = np.int32(0 if registration == "gridline" else 1)

        ds.createDimension("lat", H)
        ds.createDimension("lon", W)
        _write_coord_var(ds, "lat", lat, _LAT_ATTRS, complevel, shuffle)
        _write_coord_var(ds, "lon", lon, _LON_ATTRS, complevel, shuffle)

        for name, (arr, attrs) in fields.items():
            if "units" not in attrs:
                raise ValueError(f"field '{name}' missing required 'units' attr")
            if "long_name" not in attrs:
                raise ValueError(f"field '{name}' missing required 'long_name' attr")
            _write_data_var(ds, name, arr, attrs, complevel=complevel,
                            shuffle=shuffle, lsd=lsd, chunks=chunks_2d)
    tmp.replace(out_path)
    return out_path


def _set_global_attrs(ds, *, title, summary, comment, source, references,
                      institution, creator_name, creator_email,
                      target_age_ma, extra_globals):
    ds.Conventions = CF_CONVENTIONS
    ds.title = str(title)
    ds.summary = str(summary)
    ds.comment = str(comment)
    ds.institution = str(institution)
    ds.creator_name = str(creator_name)
    ds.creator_email = str(creator_email)
    ds.source = str(source)
    if references:
        ds.references = str(references)
    ds.date_created = _now_iso()
    ds.history = _history_line("netcdf_io.write_cf_grid", source)
    if target_age_ma is not None:
        ds.target_age_ma = np.float64(target_age_ma)
    if extra_globals:
        for k, v in extra_globals.items():
            setattr(ds, k, v)


def _write_coord_var(ds, name, arr, attrs, complevel, shuffle):
    arr = np.asarray(arr, dtype=np.float64)
    v = ds.createVariable(name, "f8", (name,),
                          zlib=True, complevel=complevel, shuffle=shuffle)
    for k, val in attrs.items():
        setattr(v, k, val)
    v.actual_range = np.array([float(arr[0]), float(arr[-1])], dtype=np.float64)
    v[:] = arr


def _write_data_var(ds, name, arr, attrs, *, complevel, shuffle, lsd, chunks):
    arr = np.asarray(arr)
    is_int = np.issubdtype(arr.dtype, np.integer)
    if is_int:
        dtype = "i1" if arr.dtype.itemsize == 1 else "i4"
    else:
        dtype = "f4"
    # Clamp chunk dims to the array shape — netCDF4 errors out if a chunk
    # dimension is larger than the corresponding data dimension (e.g.
    # default (256, 512) on a 1° 181×361 grid).
    chunks_safe = tuple(min(c, s) for c, s in zip(chunks, arr.shape))
    kwargs: dict = dict(zlib=True, complevel=complevel, shuffle=shuffle,
                        chunksizes=chunks_safe)
    if not is_int:
        kwargs["fill_value"] = np.float32("nan")
        if lsd is not None and lsd > 0:
            kwargs["least_significant_digit"] = int(lsd)
    v = ds.createVariable(name, dtype, ("lat", "lon"), **kwargs)
    for k, val in attrs.items():
        setattr(v, k, val)
    v[:] = arr.astype(dtype if dtype != "f4" else np.float32, copy=False)


# ---------------------------------------------------------------------------
# Context-manager API (rarely needed — use write_cf_grid where possible)
# ---------------------------------------------------------------------------

class _CFDataset:
    """Thin wrapper around netCDF4.Dataset that exposes the helpers above
    via a fluent interface. Yielded by open_cf_dataset()."""

    def __init__(self, ds, *, complevel, shuffle, lsd, chunks):
        self._ds = ds
        self._complevel = complevel
        self._shuffle = shuffle
        self._lsd = lsd
        self._chunks = chunks

    def set_globals(self, **kwargs):
        # Pass-through to private helper
        defaults = dict(title="", summary="", comment="", source="",
                        references="", institution=DEFAULT_INSTITUTION,
                        creator_name=DEFAULT_CREATOR_NAME,
                        creator_email=DEFAULT_CREATOR_EMAIL,
                        target_age_ma=None, extra_globals=None)
        defaults.update(kwargs)
        _set_global_attrs(self._ds, **defaults)

    def create_lat_lon(self, lat, lon):
        H, W = len(lat), len(lon)
        registration = "gridline" if (H % 2 == 1 and W % 2 == 1) else "pixel"
        self._ds.grid_registration = registration
        self._ds.node_offset = np.int32(0 if registration == "gridline" else 1)
        self._ds.createDimension("lat", H)
        self._ds.createDimension("lon", W)
        _write_coord_var(self._ds, "lat", lat, _LAT_ATTRS, self._complevel, self._shuffle)
        _write_coord_var(self._ds, "lon", lon, _LON_ATTRS, self._complevel, self._shuffle)

    def create_data_var(self, name, arr, **attrs):
        _write_data_var(self._ds, name, arr, attrs,
                        complevel=self._complevel, shuffle=self._shuffle,
                        lsd=self._lsd, chunks=self._chunks)


@contextmanager
def open_cf_dataset(out_path: Path, *,
                    complevel: int = DEFAULT_COMPLEVEL,
                    shuffle: bool = DEFAULT_SHUFFLE,
                    lsd: int | None = DEFAULT_LSD,
                    chunks_2d: tuple[int, int] = DEFAULT_CHUNK_2D,
                    overwrite: bool = True):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if overwrite and out_path.exists():
        out_path.unlink()
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    if tmp.exists():
        tmp.unlink()
    with Dataset(tmp, "w", format="NETCDF4") as raw:
        wrapper = _CFDataset(raw, complevel=complevel, shuffle=shuffle,
                             lsd=lsd, chunks=chunks_2d)
        yield wrapper
    tmp.replace(out_path)


# ---------------------------------------------------------------------------
# Existing-file amender (one-time fix for non-CF outputs from older scripts)
# ---------------------------------------------------------------------------

def amend_existing_cf_headers(
    path: Path,
    *,
    title: str | None = None,
    summary: str | None = None,
    comment: str | None = None,
    source: str | None = None,
    references: str | None = None,
    institution: str = DEFAULT_INSTITUTION,
    variable_units: dict[str, str] | None = None,
    variable_long_names: dict[str, str] | None = None,
    preserve_existing: bool = True,
) -> dict[str, int]:
    """Open an existing NetCDF file in append/edit mode and add CF-compliant
    attributes without rewriting the data. Returns a dict of counts so the
    caller can summarise what was changed.

    Always sets lat/lon attributes (units, standard_name, axis, long_name)
    if not present. Optionally sets/replaces global metadata and per-variable
    units/long_names.
    """
    counts = dict(lat_attrs_set=0, lon_attrs_set=0,
                  global_attrs_set=0, var_attrs_set=0)
    if not path.exists():
        raise FileNotFoundError(path)
    with Dataset(path, "a") as ds:
        # Lat/lon coordinate attrs
        for cname, defaults in (("lat", _LAT_ATTRS), ("lon", _LON_ATTRS)):
            if cname not in ds.variables:
                # Try common alternate names: latitude/longitude, y/x
                for alt in ("latitude", "y") if cname == "lat" else ("longitude", "x"):
                    if alt in ds.variables:
                        # We cannot rename via Dataset API easily; just add
                        # attrs to the alternate name. Note this caveat.
                        cname = alt
                        break
                else:
                    continue
            v = ds.variables[cname]
            for k, val in defaults.items():
                if preserve_existing and k in v.ncattrs():
                    continue
                setattr(v, k, val)
                counts["lat_attrs_set" if cname.startswith("lat") else
                       "lon_attrs_set"] += 1
        # Per-variable attrs
        if variable_units or variable_long_names:
            for vname, var in ds.variables.items():
                if vname in ("lat", "lon", "latitude", "longitude", "y", "x"):
                    continue
                if variable_units and vname in variable_units:
                    if not (preserve_existing and "units" in var.ncattrs()):
                        var.units = variable_units[vname]
                        counts["var_attrs_set"] += 1
                if variable_long_names and vname in variable_long_names:
                    if not (preserve_existing and "long_name" in var.ncattrs()):
                        var.long_name = variable_long_names[vname]
                        counts["var_attrs_set"] += 1
        # Global attrs
        def _set(name, val):
            if val is None:
                return
            if preserve_existing and name in ds.ncattrs() and getattr(ds, name):
                return
            setattr(ds, name, val)
            counts["global_attrs_set"] += 1
        _set("Conventions", CF_CONVENTIONS)
        _set("title", title)
        _set("summary", summary)
        _set("comment", comment)
        _set("source", source)
        _set("references", references)
        _set("institution", institution)
        # Always append a history line noting the amendment
        prior = ds.history if "history" in ds.ncattrs() else ""
        new_line = _history_line("netcdf_io.amend_existing_cf_headers", source)
        ds.history = (prior + "\n" + new_line) if prior else new_line
        ds.date_modified = _now_iso()
    return counts
